# Copyright 2016, 2017 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

matrix:
  include:
    - os: linux
      compiler: clang++-5.0
      env: TOOLSET=clang-5.0 CXXSTD=03,11,14
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libc++-dev

install:
  - BOOST_BRANCH=develop && [ "$TRAVIS_BRANCH" == "master" ] && BOOST_BRANCH=master || true
  - cd ..
  - git clone -b $BOOST_BRANCH https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init libs/config
  - git submodule update --init tools/boostdep
  - cp -r $TRAVIS_BUILD_DIR/* libs/tuple
  - python tools/boostdep/depinst/depinst.py tuple
  - ./bootstrap.sh
  - ./b2 headers

script:
  - |
    # Creating ~/user-config.jam file
    sed 's/^  //' > ~/user-config.jam << 'EOF'

    import feature os regex toolset ;

    # Extend stdlib with libc++
    feature.extend stdlib : libc++ ;
    feature.compose <stdlib>libc++ : <cxxflags>-stdlib=libc++ <linkflags>-stdlib=libc++ ;

  - ./b2 -j 3 libs/tuple/test toolset=$TOOLSET cxxstd=$CXXSTD stdlib=libc++
